import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

// Support both NODE_ENV and --prod CLI flag (for cross-platform)
const isProduction = process.env.NODE_ENV === 'production' || process.argv.includes('--prod');
const distDir = 'dist';
const folders = [
  'dist/popup',
  'dist/background',
  'dist/content',
  'dist/assets',
  'dist/utils',
  'dist/types'
];

function writeBuildEnvConfig() {
  const mode = isProduction ? 'production' : 'development';
  const enabled = isProduction ? 'false' : 'true';
  const level = isProduction ? 'warn' : 'info';
  const buildEnvPath = path.join('src', 'config', 'build-env.ts');

  const content = `// This file is generated by build.js before TypeScript compilation.\n// Do not edit manually.\n\nexport const EXTENSION_BUILD_MODE = '${mode}' as const;\nexport const DEFAULT_LOGGING_ENABLED = ${enabled};\nexport const DEFAULT_LOG_LEVEL = '${level}' as const;\n`;

  fs.writeFileSync(buildEnvPath, content, 'utf8');
  console.log(`🛠️ Wrote build config (${mode}) to ${buildEnvPath}`);
}

function logBuildSettings() {
  const mode = isProduction ? 'production' : 'development';
  const loggingEnabled = isProduction ? 'false' : 'true';
  const logLevel = isProduction ? 'warn' : 'info';

  console.log('🧾 Build logging settings:');
  console.log(`   mode: ${mode}`);
  console.log(`   loggingEnabled: ${loggingEnabled}`);
  console.log(`   logLevel: ${logLevel}`);
}

async function build() {
  const envLabel = isProduction ? '🔒 PRODUCTION' : '🔧 DEVELOPMENT';
  console.log(`🚀 Starting build... [${envLabel}]`);

  // 1. Clean dist folder
  if (fs.existsSync(distDir)) {
    console.log('🧹 Cleaning dist folder...');
    fs.rmSync(distDir, { recursive: true, force: true });
  }

  // 2. Create folders
  console.log('📁 Creating directories...');
  folders.forEach(dir => {
    fs.mkdirSync(dir, { recursive: true });
  });

  // 3. Install dependencies (skip in production for faster builds)
  if (!isProduction) {
    console.log('📥 Installing npm dependencies...');
    try {
      execSync('npm install', { stdio: 'inherit' });
    } catch (error) {
      console.error('❌ npm install failed.');
      throw error;
    }
  } else {
    console.log('⏭️  Skipping npm install (production build)');
  }

  // 4. Generate build-time runtime config
  writeBuildEnvConfig();

  // 4.1 Log the effective logging settings for this build
  logBuildSettings();

  // 5. Compile TypeScript
  console.log('📦 Compiling TypeScript...');
  try {
    execSync('npx tsc', { stdio: 'inherit' });
  } catch (error) {
    console.error('❌ TypeScript compilation failed.');
    throw error;
  }

  // 6. Copy static files
  console.log('📄 Copying static files...');
  const filesToCopy = [
    { src: 'manifest.json', dest: 'dist/manifest.json' },
    { src: 'src/popup/index.html', dest: 'dist/popup/index.html' },
    { src: 'src/popup/styles.css', dest: 'dist/popup/styles.css' },
    { src: 'src/popup/onboarding.css', dest: 'dist/popup/onboarding.css' }
  ];

  filesToCopy.forEach(({ src, dest }) => {
    if (fs.existsSync(src)) {
      fs.copyFileSync(src, dest);
    } else {
      console.warn(`⚠️ Warning: ${src} not found.`);
    }
  });

  // 7. Copy icons
  console.log('🖼️ Copying icons...');
  const assetsDir = 'assets';
  if (fs.existsSync(assetsDir)) {
    const icons = fs.readdirSync(assetsDir).filter(f => f.endsWith('.png'));
    icons.forEach(icon => {
      fs.copyFileSync(path.join(assetsDir, icon), path.join('dist/assets', icon));
    });
  } else {
    console.warn('⚠️ Warning: assets folder not found.');
  }

  console.log(`✅ Build complete! [${envLabel}]`);
}

build()
  .then(() => {
    console.log('✨ Build process ended successfully');
    process.exit(0);
  })
  .catch((err) => {
    console.error('💥 Build failed:', err.message || err);
    process.exitCode = 1;
  });