using CoverLetter.Application.Common.Interfaces;
using CoverLetter.Application.Repositories;
using CoverLetter.Domain.Common;
using MediatR;
using Microsoft.Extensions.Logging;

namespace CoverLetter.Application.UseCases.ParseCv;

/// <summary>
/// Handler for parsing CV files and persisting extracted text.
/// </summary>
public sealed class ParseCvCommandHandler : IRequestHandler<ParseCvCommand, Result<ParseCvResult>>
{
  private readonly ICvParserService _cvParserService;
  private readonly ICvRepository _cvRepository;
  private readonly IUnitOfWork _unitOfWork;
  private readonly IUserContext _userContext;
  private readonly ILogger<ParseCvCommandHandler> _logger;

  public ParseCvCommandHandler(
    ICvParserService cvParserService,
    ICvRepository cvRepository,
    IUnitOfWork unitOfWork,
    IUserContext userContext,
    ILogger<ParseCvCommandHandler> logger)
  {
    _cvParserService = cvParserService;
    _cvRepository = cvRepository;
    _unitOfWork = unitOfWork;
    _userContext = userContext;
    _logger = logger;
  }

  public async Task<Result<ParseCvResult>> Handle(ParseCvCommand request, CancellationToken cancellationToken)
  {

    var parseResult = await _cvParserService.ParseAsync(
      request.FileName,
      request.FileContent,
      request.Format,
      cancellationToken);

    if (parseResult.IsFailure)
    {
      _logger.LogWarning(
        "CV parsing failed: {FileName}, Errors: {Errors}",
        request.FileName,
        string.Join(", ", parseResult.Errors));

      return Result<ParseCvResult>.Failure(parseResult.Errors, parseResult.Type);
    }

    var userId = Guid.TryParse(_userContext.UserId, out var parsedUserId) ? parsedUserId : Guid.Empty;
    var now = DateTime.UtcNow;

    var cvDto = new CvDto
    {
      // ID will be generated by domain entity
      UserId = userId,
      FileName = request.FileName,
      Content = parseResult.Value!.ExtractedText ?? string.Empty,
      FileStoragePath = null,
      IsActive = true,
      CreatedAt = now,
      UpdatedAt = now
    };

    // Domain generates ID, repository returns entity with ID
    var createdCv = await _cvRepository.AddAsync(cvDto, cancellationToken);

    // Commit transaction using Unit of Work
    await _unitOfWork.SaveChangesAsync(cancellationToken);

    var document = parseResult.Value ?? throw new InvalidOperationException("Parsed CV document was null.");

    _logger.LogInformation(
      "Successfully parsed and persisted CV: {CvId}, Format: {Format}, Characters: {CharCount}",
      createdCv.Id,
      document.Format,
      document.Metadata.CharacterCount);

    var hyperlinks = document.Hyperlinks
      .Select(h => new HyperlinkDto(h.Url, h.DisplayText, h.Type))
      .ToList();
    var preview = document.ExtractedText.Length > 500
      ? document.ExtractedText[..500] + "..."
      : document.ExtractedText;

    var result = new ParseCvResult(
      CvId: createdCv.Id.ToString(),
      ExtractedText: document.ExtractedText,
      OriginalContent: document.OriginalContent,
      Format: document.Format,
      Metadata: document.Metadata,
      Hyperlinks: hyperlinks,
      Preview: preview);

    return Result.Success(result);
  }
}
