// This file is generated by build.js before TypeScript compilation.
// Do not edit manually.

export const EXTENSION_BUILD_MODE = 'development' as const;
export const DEFAULT_LOGGING_ENABLED = true;
export const DEFAULT_LOG_LEVEL = 'info' as const;
