import {
  DEFAULT_LOGGING_ENABLED,
  DEFAULT_LOG_LEVEL,
} from './build-env.js';

/**
 * Logging Configuration Manager
 * 
 * Three-layer configuration approach:
 * 1. Build-time defaults (from .env files) - immutable per build
 * 2. Runtime overrides (Chrome storage) - user preferences, survives extension reload
 * 3. Feature flags (future: from backend API)
 */

export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';

export interface LoggingConfig {
  /** Whether telemetry is enabled globally */
  enabled: boolean;
  /** Minimum log level to emit */
  level: LogLevel;
  /** Log telemetry events to console (useful for debugging) */
  verbose?: boolean;
  /** Source this config came from for debugging */
  source: 'defaults' | 'storage' | 'backend';
}

/**
 * Default config from build-time constants generated by build.js.
 */
const buildTimeDefaults: LoggingConfig = {
  enabled: DEFAULT_LOGGING_ENABLED,
  level: (DEFAULT_LOG_LEVEL as LogLevel),
  verbose: false,
  source: 'defaults',
};

const STORAGE_KEY = 'logging_config';

/**
 * LOGGING MANAGER
 * 
 * Usage:
 * ```typescript
 * const config = await LoggingManager.getConfig();
 * if (config.enabled) {
 *   trackExtensionEvent({ eventType: 'my_event', ... });
 * }
 * 
 * // User can toggle at runtime
 * await LoggingManager.setEnabled(false);
 * 
 * // Clear overrides and use build defaults
 * await LoggingManager.reset();
 * ```
 */
export class LoggingManager {
  /**
   * Get the current effective logging config (build defaults + storage overrides)
   */
  static async getConfig(): Promise<LoggingConfig> {
    try {
      const stored = await chrome.storage.local.get(STORAGE_KEY);
      if (stored[STORAGE_KEY]) {
        return {
          ...buildTimeDefaults,
          ...stored[STORAGE_KEY],
          source: 'storage',
        };
      }
    } catch (error) {
      console.warn('Failed to read logging config from storage:', error);
    }

    return buildTimeDefaults;
  }

  /**
   * Check if logging is currently enabled
   */
  static async isEnabled(): Promise<boolean> {
    const config = await this.getConfig();
    return config.enabled;
  }

  /**
   * Override logging enabled state at runtime
   */
  static async setEnabled(enabled: boolean): Promise<void> {
    try {
      const current = await this.getConfig();
      await chrome.storage.local.set({
        [STORAGE_KEY]: {
          ...current,
          enabled,
          source: 'storage',
        },
      });
      console.log(`[Logging Config] Logging ${enabled ? 'enabled' : 'disabled'}`);
    } catch (error) {
      console.error('Failed to set logging config:', error);
    }
  }

  /**
   * Set log level at runtime
   */
  static async setLogLevel(level: LogLevel): Promise<void> {
    try {
      const current = await this.getConfig();
      await chrome.storage.local.set({
        [STORAGE_KEY]: {
          ...current,
          level,
          source: 'storage',
        },
      });
      console.log(`[Logging Config] Log level set to ${level}`);
    } catch (error) {
      console.error('Failed to set log level:', error);
    }
  }

  /**
   * Enable verbose console logging (for debugging)
   */
  static async setVerbose(verbose: boolean): Promise<void> {
    try {
      const current = await this.getConfig();
      await chrome.storage.local.set({
        [STORAGE_KEY]: {
          ...current,
          verbose,
          source: 'storage',
        },
      });
      console.log(`[Logging Config] Verbose mode ${verbose ? 'enabled' : 'disabled'}`);
    } catch (error) {
      console.error('Failed to set verbose mode:', error);
    }
  }

  /**
   * Reset to build-time defaults (clear storage overrides)
   */
  static async reset(): Promise<void> {
    try {
      await chrome.storage.local.remove(STORAGE_KEY);
      console.log('[Logging Config] Reset to build-time defaults');
    } catch (error) {
      console.error('Failed to reset logging config:', error);
    }
  }

  /**
   * Debug helper: print current config to console
   */
  static async printConfig(): Promise<void> {
    const config = await this.getConfig();
    console.table({
      'Logging Enabled': config.enabled,
      'Log Level': config.level,
      'Verbose': config.verbose,
      'Source': config.source,
      'Build Defaults': buildTimeDefaults,
    });
  }
}

/**
 * Check if a log level passes the filter
 * 
 * Order: debug < info < warn < error < off
 */
export function passesLogLevelFilter(currentLevel: LogLevel, eventLevel: LogLevel): boolean {
  const levels = { debug: 0, info: 1, warn: 2, error: 3, off: 4 };
  return levels[eventLevel] >= levels[currentLevel];
}
